[package]
name = "crsf"
edition = "2021"
version = "2.0.1"
authors = ["Dicu Tudor <tudor@dicu.org>"]
license = "MIT"
description = "This crate provides a #[no_std] parser for the crossfire protocol."
repository = "https://github.com/tact1m4n3/crsf-rs"
documentation = "https://docs.rs/crsf"

[dependencies]
bitfield = "0.14"
crc = "3.0"
defmt = { version = "0.3.6", optional = true }
snafu = { version = "0.8.0", default-features = false }

[dev-dependencies]
serialport = "4.2.2"

[features]
defmt = ["dep:defmt"]
